// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMmUbhnXdXXyK7r4py6a0lK04b4rCOrkA',
    appId: '1:310559490686:web:6b4cfd3c5f6b050d930e2f',
    messagingSenderId: '310559490686',
    projectId: 'laundrymanagement-f17c9',
    authDomain: 'laundrymanagement-f17c9.firebaseapp.com',
    storageBucket: 'laundrymanagement-f17c9.firebasestorage.app',
    measurementId: 'G-C4L1EFZ2W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnXa6uf-3ww7dpL3QwQLyLodkuAinw80Y',
    appId: '1:310559490686:android:3e7e9c30a203d979930e2f',
    messagingSenderId: '310559490686',
    projectId: 'laundrymanagement-f17c9',
    storageBucket: 'laundrymanagement-f17c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA3xas6OnBemfk4XYxVQQtHkQSqntra1w',
    appId: '1:310559490686:ios:8361d914647df3a9930e2f',
    messagingSenderId: '310559490686',
    projectId: 'laundrymanagement-f17c9',
    storageBucket: 'laundrymanagement-f17c9.firebasestorage.app',
    iosBundleId: 'com.example.ironingboy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA3xas6OnBemfk4XYxVQQtHkQSqntra1w',
    appId: '1:310559490686:ios:8361d914647df3a9930e2f',
    messagingSenderId: '310559490686',
    projectId: 'laundrymanagement-f17c9',
    storageBucket: 'laundrymanagement-f17c9.firebasestorage.app',
    iosBundleId: 'com.example.ironingboy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMmUbhnXdXXyK7r4py6a0lK04b4rCOrkA',
    appId: '1:310559490686:web:5eadc4319edb2241930e2f',
    messagingSenderId: '310559490686',
    projectId: 'laundrymanagement-f17c9',
    authDomain: 'laundrymanagement-f17c9.firebaseapp.com',
    storageBucket: 'laundrymanagement-f17c9.firebasestorage.app',
    measurementId: 'G-ZS1X5Y7SBG',
  );
}
